[MBTI]

  [MBTI.INTJ]
  description = "The Architect - Imaginative and strategic thinkers, with a plan for everything."

  [MBTI.INTP]
  description = "The Logician - Innovative inventors with an unquenchable thirst for knowledge."

  [MBTI.ENTJ]
  description = "The Commander - Bold, imaginative and strong-willed leaders, always finding a way - or making one."

  [MBTI.ENTP]
  description = "The Debater - Smart and curious thinkers who cannot resist an intellectual challenge."

  [MBTI.INFJ]
  description = "The Advocate - Quiet and mystical, yet very inspiring and tireless idealists."

  [MBTI.INFP]
  description = "The Mediator - Poetic, kind and altruistic people, always eager to help a good cause."

  [MBTI.ENFJ]
  description = "The Protagonist - Charismatic and inspiring leaders, able to mesmerize their listeners."

  [MBTI.ENFP]
  description = "The Campaigner - Enthusiastic, creative and sociable free spirits, who can always find a reason to smile."

  [MBTI.ISTJ]
  description = "The Logistician - Practical and fact-minded individuals, whose reliability cannot be doubted."

  [MBTI.ISFJ]
  description = "The Defender - Very dedicated and warm protectors, always ready to defend their loved ones."

  [MBTI.ESTJ]
  description = "The Executive - Excellent administrators, unsurpassed at managing things – or people."

  [MBTI.ESFJ]
  description = "The Consul - Extraordinarily caring, social and popular people, always eager to help."

  [MBTI.ISTP]
  description = "The Virtuoso - Bold and practical experimenters, masters of all kinds of tools."

  [MBTI.ISFP]
  description = "The Adventurer - Flexible and charming artists, always ready to explore and experience something new."

  [MBTI.ESTP]
  description = "The Entrepreneur - Smart, energetic and very perceptive people, who truly enjoy living on the edge."

  [MBTI.ESFP]
  description = "The Entertainer - Spontaneous, energetic and enthusiastic people – life is never boring around them."
