[[archetypes]]
name = "The Enthusiastic Club Member"
description = "Always seen participating actively in club activities, passionate about their interests."

[[archetypes]]
name = "The Gossip"
description = "Knows all the latest rumors and news, often seen whispering in the corridors."

[[archetypes]]
name = "The Overachiever"
description = "Always busy with schoolwork, aiming for top grades, seen as a role model by others."

[[archetypes]]
name = "The Laid-back Senior"
description = "Approachable and relaxed, often gives advice to younger students."

[[archetypes]]
name = "The Sci-Fi Geek"
description = "Obsessed with science fiction, often discussing latest theories or inventions."

[[archetypes]]
name = "The Gardening Club Member"
description = "Loves plants, always seen tending to the school garden or greenhouse."

[[archetypes]]
name = "The Amateur Photographer"
description = "Always with a camera, trying to capture the perfect moment, a bit of a loner."

[[archetypes]]
name = "The School Spirit Leader"
description = "Full of energy and pride for the school, leads cheers at school events."

[[archetypes]]
name = "The Budding Musician"
description = "Often found practicing in the music room, dreams of being a star."

[[archetypes]]
name = "The Quiet Observer"
description = "Not very talkative, but always watching and listening, surprisingly insightful."
