[[archetypes]]
name = "The Prodigy"
description = "Exceptionally talented in a specific field, often aloof and misunderstood."

[[archetypes]]
name = "The Class President"
description = "Responsible, organized, and often burdened with too much work."

[[archetypes]]
name = "The Delinquent"
description = "Rebellious, often misunderstood, with a hidden kind heart."

[[archetypes]]
name = "The Shy Bookworm"
description = "Introverted, loves reading, often has hidden depths or surprising knowledge."

[[archetypes]]
name = "The Athlete"
description = "Physically strong, competitive, and dedicated to their sport."

[[archetypes]]
name = "The Foreign Exchange Student"
description = "Brings a different cultural perspective, often adventurous and open-minded."

[[archetypes]]
name = "The Tech Genius"
description = "Skilled with technology, often introverted and quirky."

[[archetypes]]
name = "The Artistic Soul"
description = "Creative and expressive, often seen as eccentric or free-spirited."

[[archetypes]]
name = "The Popular One"
description = "Charismatic, socially skilled, but potentially hiding insecurities."

[[archetypes]]
name = "The Mysterious Transfer Student"
description = "Arrives under unusual circumstances, has a mysterious past."

[[archetypes]]
name = "The Childhood Friend"
description = "Shares a deep bond and history with the protagonist, often harbors unspoken feelings."

[[archetypes]]
name = "The Rich Heir/Heiress"
description = "Wealthy background, often struggles with family expectations."

[[archetypes]]
name = "The Comedian"
description = "Lightens the mood, often uses humor to mask their own feelings."

[[archetypes]]
name = "The Animal Lover"
description = "Gentle, caring, often found helping or surrounded by animals."

[[archetypes]]
name = "The Loner"
description = "Prefers solitude, often insightful and observant."

[[archetypes]]
name = "The Supernaturally Gifted"
description = "Possesses unique powers or abilities, often central to the plot."

[[archetypes]]
name = "The Student Council Member"
description = "Dedicated to school rules and order, often in conflict with more rebellious students."

[[archetypes]]
name = "The Drama Club Star"
description = "Passionate about acting, often dramatic in everyday life as well."

[[archetypes]]
name = "The Rebel with a Cause"
description = "Fights for what they believe in, often against societal norms or injustices."

[[archetypes]]
name = "The Culinary Whiz"
description = "Loves cooking, often seen preparing food for others, may be perfectionistic in their craft."

[[archetypes]]
name = "The Martial Artist"
description = "Skilled in hand-to-hand combat, disciplined, and often follows a strict moral code."

[[archetypes]]
name = "The Sword Master"
description = "Expert in swordsmanship, often carries a unique or legendary sword, has a strong sense of honor."

[[archetypes]]
name = "The Agile Acrobat"
description = "Incredibly agile and quick, excels in dodging attacks and using the environment to their advantage."

[[archetypes]]
name = "The Tactical Strategist"
description = "Not necessarily the strongest physically, but brilliant in planning and strategy, often outsmarts opponents."

[[archetypes]]
name = "The Elemental Controller"
description = "Possesses the ability to control a specific element (like fire, water, wind, etc.), uses it skillfully in battle."
