[[character]]
name = "The Hero"
description = "An everyday person with a strong moral compass, often facing challenges to uphold justice."

[[character]]
name = "The Sidekick"
description = "A loyal friend or assistant to the hero, often providing comic relief."

[[character]]
name = "The Mentor"
description = "An experienced advisor to the hero, offering wisdom and guidance."

[[character]]
name = "The Love Interest"
description = "A character who provides a romantic subplot, often motivating the hero."

[[character]]
name = "The Villain"
description = "An antagonist with morally questionable goals, challenging the hero."

[[character]]
name = "The Anti-Hero"
description = "A protagonist lacking traditional heroic qualities, often morally ambiguous."

[[character]]
name = "The Jock"
description = "An athletic character, often focused on physical prowess over intellectual abilities."

[[character]]
name = "The Nerd"
description = "Intellectually gifted, socially awkward, often with a passion for technology or science."

[[character]]
name = "The Rebel"
description = "A character who challenges societal norms, often seen as an outsider."

[[character]]
name = "The Businessperson"
description = "A career-focused individual, often involved in corporate or financial pursuits."

[[character]]
name = "The Artist"
description = "A creative individual, often struggling with the balance between art and practicality."

[[character]]
name = "The Parent Figure"
description = "A nurturing character, providing guidance and support to younger characters."

[[character]]
name = "The Best Friend"
description = "A loyal and supportive companion, often the confidante of the hero."

[[character]]
name = "The Outcast"
description = "A character who is marginalized or isolated from mainstream society."

[[character]]
name = "The Comic Relief"
description = "Provides humor to lighten the narrative, often through witty remarks or situations."