[family_secret_aspirations]
aspiration1 = "Building a hidden lab for forbidden experiments."
aspiration2 = "Becoming the secret benefactors of the city's vigilantes."
aspiration3 = "Restoring a long-lost, powerful family heirloom."
aspiration4 = "Creating an underground network for arcane knowledge."
aspiration5 = "Establishing a covert alliance with a mythical entity."
aspiration6 = "Hiding a revolutionary invention from prying eyes."
aspiration7 = "Mastering an ancient, almost forgotten martial art."
aspiration8 = "Amassing a secret collection of otherworldly artifacts."
aspiration9 = "Fostering a prodigy child in a clandestine discipline."
aspiration10 = "Running an undercover vigilante group."
aspiration11 = "Unearthing the truth behind a city-wide conspiracy."
aspiration12 = "Harboring a fugitive with a mysterious past."
aspiration13 = "Protecting a secret garden with magical properties."
aspiration14 = "Developing a cure for a rare, unknown disease."
aspiration15 = "Maintaining a hidden room with alter egos."
aspiration16 = "Keeping a centuries-old tradition alive in secrecy."
aspiration17 = "Guarding a map to a legendary, lost city."
aspiration18 = "Concealing a pact with a powerful spirit."
aspiration19 = "Preserving the knowledge of a forbidden language."
aspiration20 = "Training in secret for an underground competition."

[family_secret_skeletons]
skeleton1 = "A past member was a notorious thief."
skeleton2 = "Ancestors were part of a failed rebellion."
skeleton3 = "A hidden room that was once a crime scene."
skeleton4 = "Covering up an accidental discovery of a cursed object."
skeleton5 = "A family member vanished under mysterious circumstances."
skeleton6 = "Involvement in a scandal that almost destroyed the city."
skeleton7 = "An unspoken feud with another influential family."
skeleton8 = "A secret marriage that would scandalize the community."
skeleton9 = "Bearing the shame of a failed experiment that went awry."
skeleton10 = "Harboring resentment against a city hero."
skeleton11 = "A debt owed to a dubious organization."
skeleton12 = "A false identity used to escape a dark past."
skeleton13 = "The disappearance of a valuable family artifact."
skeleton14 = "A hidden addiction that's tearing the family apart."
skeleton15 = "Betrayal of a close friend for personal gain."
skeleton16 = "A pact made with a malevolent force."
skeleton17 = "Falsifying family lineage to hide a humble origin."
skeleton18 = "A secret study into forbidden magical practices."
skeleton19 = "Destroying evidence of an ancient family curse."
skeleton20 = "A hidden affair that threatens family unity."