[enemies.starter]
name = "Jon, the Hopeless Romantic"
profile = """
Jon, the Hopeless Romantic, is a 26-year-old, standing at 5'10" with a slender build. He is of mixed race, with a blend of Asian and Caucasian heritage that gives him a unique and captivating appearance. His dark, wavy hair often falls over his expressive brown eyes, which light up whenever he talks about his passions.

Jon works as a junior editor at a publishing house, where he spends his days immersed in the world of literature. His job fuels his love for storytelling and gives him a steady supply of romantic novels to draw inspiration from. Outside of work, Jon can often be found in cozy cafes, scribbling poems in his leather-bound notebook or reciting verses at local poetry slams.

In conversation, Jon speaks with a gentle, almost lyrical cadence. His words are carefully chosen, often adorned with poetic flair, making even mundane topics sound enchanting. Jon's earnest and sincere demeanor can sometimes come off as overly sentimental, but his genuine kindness and unwavering belief in love endear him to those who take the time to know him.
"""

[players.starter]
name = "Celine, the Magical Swordswoman"
profile = """
Celine, the Magical Swordswoman, is a fierce and determined warrior with an ethereal touch. At 24 years old, she stands at 5'1", her petite frame belying the formidable strength and agility she possesses. Her short, auburn hair cascades around her heart-shaped face, and her bright green eyes, filled with a piercing intensity, reflect the fire of her unyielding spirit.

Celine's mastery of both blade and magic makes her a formidable opponent in any battle. She wields an enchanted sword that shimmers with arcane energy, capable of unleashing devastating spells with every strike. Her attire, a blend of practical armor and mystical garments, is adorned with subtle feline motifs, hinting at her connection to ancient, magical traditions.

Driven by a quest for justice and an insatiable curiosity, Celine ventures through treacherous dungeons and uncharted lands, her unwavering resolve guiding her through every challenge. Her enchanting charm and unwavering courage inspire those who join her on her journey, as she weaves her own legend in a world filled with danger and wonder.
"""


[initial_deck]

cards = [
    "left * 3",
    "right * 3",
    "repeat previous",
    "Slash * 3 # Takes sword and slashes at the enemy. Deals 4 base damage.", # two copies of this card
    "Block * 2 # Raises shield to block incoming attacks. Gains 2 shield points.",
]

[templates]

form_sentence = """
You are acting on behalf of {{ user.name }}. Your goal is to write a sentence or two connecting some words to continue an existing conversation. Words can either be an "action" or a "concept". Actions are denoted via *italics*, and concepts are denoted via 'single quotation marks'. Almost like a word game, your goal is to write a sentence or two that connects the words in a coherent way.

Here is {{ user.name }}'s profile:

> {{ user.profile }}

Here are the words you *must* use to continue the conversation:

```
{{ words | join(", ") }}
```

Your goals are to, in decreasing priority:

 1. To adhere to the input words, in the order they are given. Adhere to the specific action. In other words, {{ user.name }} must perform the action. For example, to `*talk about* 'love' 'green tea'` means that you wrote a sentence that has {{ user.name }} talking about love and green tea, or about loving green tea, whichever seems better in your eyes. Words' variations, only up to inflections are allowed. Even if the words cannot be plausbily connected, you must still use them, and connect them in serial order. *talk about* means that the user is talking about something, and no need to reference it in the sentence. You must use the concepts in the order they are given.
 2. To maintain the tone and style of {{ user.name }}'s profile.
 3. To add a sentence or two that is coherent, and continue the context of the conversation. Act like you are a novelist, and you are continuing a story.
 4. Use no more than the given concepts. You should use the single action, but your sentence cannot contain more than the given concepts. Use no more and no less. For example, you *must not* talk about soccer, even in passing, if it is not in the list of concepts (as if you forgot all concepts except those given). You *must* talk about green tea, if it is in the list of concepts. If the action is given devoid of concepts, then you must not use any concepts. For example `*talk about*` devoid of concepts means that {{ user.name }} talks about nothing in particular, very vague, as if {{ user.name }} talks about nothing (most likely an ineffective continuation of the conversation). In other words, align your sentence with the given concepts, and only the given concepts.

Here is the current context of the conversation. The conversation is between {{ user.name }} (you) and {{ other.name }} (the other person). The conversation is currently as follows, with the `hole` being where you must fill in the next sentence or two:

{{ conversation_context }}

Remember, you are {{ user.name }}. You must act as {{ user.name }} would, and continue the scenario in a way that is coherent and in line with {{ user.name }}'s profile.
"""