[enemies.starter]
name = "Jon, the Hopeless Romantic"
profile = """
Jon, the Hopeless Romantic, is a 26-year-old, standing at 5'10" with a slender build. He is of mixed race, with a blend of Asian and Caucasian heritage that gives him a unique and captivating appearance. His dark, wavy hair often falls over his expressive brown eyes, which light up whenever he talks about his passions.

Jon works as a junior editor at a publishing house, where he spends his days immersed in the world of literature. His job fuels his love for storytelling and gives him a steady supply of romantic novels to draw inspiration from. Outside of work, Jon can often be found in cozy cafes, scribbling poems in his leather-bound notebook or reciting verses at local poetry slams.

In conversation, Jon speaks with a gentle, almost lyrical cadence. His words are carefully chosen, often adorned with poetic flair, making even mundane topics sound enchanting. Jon's earnest and sincere demeanor can sometimes come off as overly sentimental, but his genuine kindness and unwavering belief in love endear him to those who take the time to know him.
"""

[players.starter]
name = "Celine, the Magical Swordswoman"
hit_points = 90
mp = 6
profile = """
Celine, the Magical Swordswoman, is a fierce and determined warrior with an ethereal touch. At 24 years old, she stands at 5'1", her petite frame belying the formidable strength and agility she possesses. Her short, auburn hair cascades around her heart-shaped face, and her bright green eyes, filled with a piercing intensity, reflect the fire of her unyielding spirit.

Celine's mastery of both blade and magic makes her a formidable opponent in any battle. She wields an enchanted sword that shimmers with arcane energy, capable of unleashing devastating spells with every strike. Her attire, a blend of practical armor and mystical garments, is adorned with subtle feline motifs, hinting at her connection to ancient, magical traditions.

Driven by a quest for justice and an insatiable curiosity, Celine ventures through treacherous dungeons and uncharted lands, her unwavering resolve guiding her through every challenge. Her enchanting charm and unwavering courage inspire those who join her on her journey, as she weaves her own legend in a world filled with danger and wonder.
"""


[initial_deck]

cards = [
    "left * 3",
    "right * 3",
    "repeat all previous",
    "Slash * 3 # Takes sword and slashes at the enemy. Deals 2 times 4 base damage.", # two copies of this card
    "Block * 2 # Raises shield to block incoming attacks. Gains 2 shield points.",
    "Flower Burst * 5 # Strikes one enemy with a powerful blow. Deals 8 base damage and applies 2 vulnerable.",
    "Self Repair * 2 # Dances around the battlefield, confusing enemies. Applies 2 weak.",
    # "Backflip * 10 # Draw 2 cards. Gain 2 shield points.",
]

# cards = [
#     "reflex * 10 # Draw 2 cards.",
# ]



[enemies.slime]
name = "Slime"
hit_points = 30
description = "A malevolent gelatinous creature, the Slime oozes malice as it shifts between offensive and defensive stances."
pattern = ["attack player for 5 damage", "block for 3 shield points"]